/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { 080f057905dc32d2f11065d606dc4cd6200Links } from './080f057905dc32d2f11065d606dc4cd6200Links';
import type { 080f057905dc32d2f11065d606dc4cd6200Meta } from './080f057905dc32d2f11065d606dc4cd6200Meta';
import type { Product } from './product';

export type 080f057905dc32d2f11065d606dc4cd6200 = {
  data?: Product[];
  meta?: 080f057905dc32d2f11065d606dc4cd6200Meta;
  links?: 080f057905dc32d2f11065d606dc4cd6200Links;
};
