/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */

export type 080f057905dc32d2f11065d606dc4cd6Params = {
/**
 * Filter by name or SKU
 */
search?: string;
/**
 * Filter by category
 */
category_id?: number;
/**
 * Filter by active status
 */
is_active?: boolean;
/**
 * Items per page (1–100)
 */
per_page?: number;
page?: number;
};
