/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export type 08136088c4862c313b35d6518bab8d3a201 = {
  data?: User;
  token?: string;
};
