/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */

export type 2ce632b9d1c0c445557821d09add7ec2Body = {
  sku?: string;
  name?: string;
  /** @nullable */
  description?: string | null;
  price?: number;
  stock_quantity?: number;
  low_stock_threshold?: number;
  is_active?: boolean;
  category_id?: number;
};
