/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { Category } from './category';

export type 486849467f411ec5e4bdf111f50ede87200 = {
  data?: Category;
};
