/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */

export type 76ae5d23055c902990a04b0ff6b58598BodyReason = typeof 76ae5d23055c902990a04b0ff6b58598BodyReason[keyof typeof 76ae5d23055c902990a04b0ff6b58598BodyReason];


export const 76ae5d23055c902990a04b0ff6b58598BodyReason = {
  purchase: 'purchase',
  return: 'return',
  device_scanned: 'device_scanned',
  sale: 'sale',
  damage: 'damage',
  expired: 'expired',
  correction: 'correction',
  initial_stock: 'initial_stock',
} as const;
