/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { StockTransaction } from './stockTransaction';

export type 76ae5d23055c902990a04b0ff6b58598201 = {
  data?: StockTransaction;
};
