/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { 76ae5d23055c902990a04b0ff6b58598BodyReason } from './76ae5d23055c902990a04b0ff6b58598BodyReason';
import type { 76ae5d23055c902990a04b0ff6b58598BodyType } from './76ae5d23055c902990a04b0ff6b58598BodyType';

export type 76ae5d23055c902990a04b0ff6b58598Body = {
  product_id: number;
  type: 76ae5d23055c902990a04b0ff6b58598BodyType;
  reason: 76ae5d23055c902990a04b0ff6b58598BodyReason;
  quantity: number;
  /** @nullable */
  notes?: string | null;
};
