/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { 86cd38e4ff52906c67b60389af1f947d200Links } from './86cd38e4ff52906c67b60389af1f947d200Links';
import type { 86cd38e4ff52906c67b60389af1f947d200Meta } from './86cd38e4ff52906c67b60389af1f947d200Meta';
import type { StockTransaction } from './stockTransaction';

export type 86cd38e4ff52906c67b60389af1f947d200 = {
  data?: StockTransaction[];
  meta?: 86cd38e4ff52906c67b60389af1f947d200Meta;
  links?: 86cd38e4ff52906c67b60389af1f947d200Links;
};
