/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export type 99d66635c4992aeaa6aa44ff653d0563200 = {
  data?: User;
  token?: string;
};
