/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */

export type Aa9becd18deeb9772b41e7a04c6a2700BodyType = typeof Aa9becd18deeb9772b41e7a04c6a2700BodyType[keyof typeof Aa9becd18deeb9772b41e7a04c6a2700BodyType];


export const Aa9becd18deeb9772b41e7a04c6a2700BodyType = {
  in: 'in',
  out: 'out',
  adjustment: 'adjustment',
} as const;
