/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */

export type Aa9becd18deeb9772b41e7a04c6a2700BodyDeviceType = typeof Aa9becd18deeb9772b41e7a04c6a2700BodyDeviceType[keyof typeof Aa9becd18deeb9772b41e7a04c6a2700BodyDeviceType];


export const Aa9becd18deeb9772b41e7a04c6a2700BodyDeviceType = {
  barcode_scanner: 'barcode_scanner',
  weighing_scale: 'weighing_scale',
} as const;
