/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { Aa9becd18deeb9772b41e7a04c6a2700BodyDeviceType } from './aa9becd18deeb9772b41e7a04c6a2700BodyDeviceType';
import type { Aa9becd18deeb9772b41e7a04c6a2700BodyType } from './aa9becd18deeb9772b41e7a04c6a2700BodyType';

export type Aa9becd18deeb9772b41e7a04c6a2700Body = {
  device_id: string;
  device_type: Aa9becd18deeb9772b41e7a04c6a2700BodyDeviceType;
  product_id: number;
  quantity: number;
  type: Aa9becd18deeb9772b41e7a04c6a2700BodyType;
  /** @nullable */
  notes?: string | null;
};
