/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */

export type AuditLogsListParams = {
subject_type?: string;
subject_id?: number;
causer_id?: number;
per_page?: number;
};
