/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { AuditLog } from './auditLog';
import type { AuditLogsList200Links } from './auditLogsList200Links';
import type { AuditLogsList200Meta } from './auditLogsList200Meta';

export type AuditLogsList200 = {
  data?: AuditLog[];
  meta?: AuditLogsList200Meta;
  links?: AuditLogsList200Links;
};
