/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */

export interface Category {
  id?: number;
  name?: string;
  slug?: string;
  /** @nullable */
  description?: string | null;
  is_active?: boolean;
  created_at?: string;
  updated_at?: string;
}
