/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */

export type DeviceWebhookBodyDeviceType = typeof DeviceWebhookBodyDeviceType[keyof typeof DeviceWebhookBodyDeviceType];


export const DeviceWebhookBodyDeviceType = {
  barcode_scanner: 'barcode_scanner',
  weighing_scale: 'weighing_scale',
} as const;
