/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { DeviceWebhookBodyDeviceType } from './deviceWebhookBodyDeviceType';
import type { DeviceWebhookBodyType } from './deviceWebhookBodyType';

export type DeviceWebhookBody = {
  device_id: string;
  device_type: DeviceWebhookBodyDeviceType;
  product_id: number;
  quantity: number;
  type: DeviceWebhookBodyType;
  /** @nullable */
  notes?: string | null;
};
