/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { Category } from './category';

export interface Product {
  id?: number;
  sku?: string;
  name?: string;
  /** @nullable */
  description?: string | null;
  price?: number;
  stock_quantity?: number;
  low_stock_threshold?: number;
  is_low_stock?: boolean;
  is_active?: boolean;
  category?: Category;
  created_at?: string;
  updated_at?: string;
}
