/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { Product } from './product';
import type { ProductsList200Links } from './productsList200Links';
import type { ProductsList200Meta } from './productsList200Meta';

export type ProductsList200 = {
  data?: Product[];
  meta?: ProductsList200Meta;
  links?: ProductsList200Links;
};
