/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { Product } from './product';
import type { StockTransactionReason } from './stockTransactionReason';
import type { StockTransactionType } from './stockTransactionType';
import type { User } from './user';

export interface StockTransaction {
  id?: number;
  type?: StockTransactionType;
  reason?: StockTransactionReason;
  quantity?: number;
  stock_before?: number;
  stock_after?: number;
  /** @nullable */
  notes?: string | null;
  product?: Product;
  performed_by?: User;
  created_at?: string;
}
