/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Inventory API
 * Inventory & Stock Management REST API — Repository + Service pattern, domain events, HMAC device webhooks, audit trail.
 * OpenAPI spec version: 1.0.0
 */
import type { StockTransaction } from './stockTransaction';
import type { StockTransactionsList200Links } from './stockTransactionsList200Links';
import type { StockTransactionsList200Meta } from './stockTransactionsList200Meta';

export type StockTransactionsList200 = {
  data?: StockTransaction[];
  meta?: StockTransactionsList200Meta;
  links?: StockTransactionsList200Links;
};
